"""This file was generated by scripts/endpoint_codegen/code_generation.py. Do not edit by hand -- re-run the generating script instead."""

from __future__ import annotations

import random
from abc import ABC, abstractmethod
from typing import Annotated, Literal

from pandas import DataFrame
from pydantic import BaseModel, Field

from graphdatascience.graph.graph_api import Graph
from graphdatascience.procedure_surface.api.base_result import MutateResult, NodeResult, StatsResult, WriteResult
from graphdatascience.procedure_surface.api.descriptions import RANDOM_SEED_DESCRIPTION, TASK_NAME_DESCRIPTION
from graphdatascience.procedure_surface.api.embedding.config import (
    FastRPConfig,
    IdentityConfig,
    NoTrainGraphEncoderConfig,
)
from graphdatascience.procedure_surface.api.job_handle import JobHandle


class EncodeEndpoints(ABC):
    @abstractmethod
    def compute(
        self,
        G: Graph,
        *,
        graph_encoder: str | (FastRPConfig | IdentityConfig),
        random_seed: int | None = None,
        job_id: str | None = None,
        node_labels: list[str] = ["*"],
        relationship_types: list[str] = ["*"],
        feature_properties: list[str],
    ) -> JobHandle:
        """
        Parameters
        ----------
        G
            The graph to run the procedure on.
        graph_encoder
            Encoder used to produce node embeddings: either the name of a previously trained encoder model, or an inline configuration for a non-trainable encoder (e.g. FastRP or Identity).
        random_seed
            Seed for random number generation to ensure reproducible results.
        job_id
            Identifier to track the job by. Generated by the server if not specified.
        node_labels
            List of node labels to include in the job configuration.
        relationship_types
            List of relationship types to include in the job configuration.
        feature_properties
            List of features to include in the job configuration.

        Returns
        -------
        JobHandle
        """

    @abstractmethod
    def stream(
        self,
        G: Graph,
        *,
        graph_encoder: str | (FastRPConfig | IdentityConfig),
        random_seed: int | None = None,
        job_id: str | None = None,
        node_labels: list[str] = ["*"],
        relationship_types: list[str] = ["*"],
        feature_properties: list[str],
    ) -> DataFrame:
        """
        Parameters
        ----------
        G
            The graph to run the procedure on.
        graph_encoder
            Encoder used to produce node embeddings: either the name of a previously trained encoder model, or an inline configuration for a non-trainable encoder (e.g. FastRP or Identity).
        random_seed
            Seed for random number generation to ensure reproducible results.
        job_id
            Identifier to track the job by. Generated by the server if not specified.
        node_labels
            List of node labels to include in the job configuration.
        relationship_types
            List of relationship types to include in the job configuration.
        feature_properties
            List of features to include in the job configuration.

        Returns
        -------
        DataFrame
        """

    @abstractmethod
    def mutate(
        self,
        G: Graph,
        *,
        graph_encoder: str | (FastRPConfig | IdentityConfig),
        random_seed: int | None = None,
        mutate_property: str,
        job_id: str | None = None,
        node_labels: list[str] = ["*"],
        relationship_types: list[str] = ["*"],
        feature_properties: list[str],
    ) -> EncodeMutateResults:
        """
        Parameters
        ----------
        G
            The graph to run the procedure on.
        graph_encoder
            Encoder used to produce node embeddings: either the name of a previously trained encoder model, or an inline configuration for a non-trainable encoder (e.g. FastRP or Identity).
        random_seed
            Seed for random number generation to ensure reproducible results.
        mutate_property
            Name of the node property to store the result in, on the in-memory graph.
        job_id
            Identifier to track the job by. Generated by the server if not specified.
        node_labels
            List of node labels to include in the job configuration.
        relationship_types
            List of relationship types to include in the job configuration.
        feature_properties
            List of features to include in the job configuration.

        Returns
        -------
        EncodeMutateResults
        """

    @abstractmethod
    def stats(
        self,
        G: Graph,
        *,
        graph_encoder: str | (FastRPConfig | IdentityConfig),
        random_seed: int | None = None,
        job_id: str | None = None,
        node_labels: list[str] = ["*"],
        relationship_types: list[str] = ["*"],
        feature_properties: list[str],
    ) -> EncodeStatsResult:
        """
        Parameters
        ----------
        G
            The graph to run the procedure on.
        graph_encoder
            Encoder used to produce node embeddings: either the name of a previously trained encoder model, or an inline configuration for a non-trainable encoder (e.g. FastRP or Identity).
        random_seed
            Seed for random number generation to ensure reproducible results.
        job_id
            Identifier to track the job by. Generated by the server if not specified.
        node_labels
            List of node labels to include in the job configuration.
        relationship_types
            List of relationship types to include in the job configuration.
        feature_properties
            List of features to include in the job configuration.

        Returns
        -------
        EncodeStatsResult
        """

    @abstractmethod
    def write(
        self,
        G: Graph,
        *,
        graph_encoder: str | (FastRPConfig | IdentityConfig),
        random_seed: int | None = None,
        write_property: str,
        write_concurrency: int,
        job_id: str | None = None,
        node_labels: list[str] = ["*"],
        relationship_types: list[str] = ["*"],
        feature_properties: list[str],
    ) -> EncodeWriteResult:
        """
        Parameters
        ----------
        G
            The graph to run the procedure on.
        graph_encoder
            Encoder used to produce node embeddings: either the name of a previously trained encoder model, or an inline configuration for a non-trainable encoder (e.g. FastRP or Identity).
        random_seed
            Seed for random number generation to ensure reproducible results.
        write_property
            Name of the node property to write the result to, in the database.
        write_concurrency
            Number of concurrent nodes to write in the database.
        job_id
            Identifier to track the job by. Generated by the server if not specified.
        node_labels
            List of node labels to include in the job configuration.
        relationship_types
            List of relationship types to include in the job configuration.
        feature_properties
            List of features to include in the job configuration.

        Returns
        -------
        EncodeWriteResult
        """


class EncodeConfig(BaseModel):
    task_name: Literal["gml_encode"] = Field(
        "gml_encode", validation_alias="taskName", description=TASK_NAME_DESCRIPTION
    )
    graph_encoder: str | Annotated[NoTrainGraphEncoderConfig, Field(discriminator="graph_encoder_type")] = Field(
        description="Encoder used to produce node embeddings: either the name of a previously trained encoder model, or an inline configuration for a non-trainable encoder (e.g. FastRP or Identity)."
    )
    random_seed: int = Field(default_factory=lambda: random.randint(0, 2**32 - 1), description=RANDOM_SEED_DESCRIPTION)


class EncodeMutateResults(MutateResult, NodeResult):
    pass


class EncodeStatsResult(StatsResult, NodeResult):
    pass


class EncodeWriteResult(WriteResult, NodeResult):
    pass
