"""This file was generated by scripts/endpoint_codegen/code_generation.py. Do not edit by hand -- re-run the generating script instead."""

from __future__ import annotations

import random
from abc import ABC, abstractmethod
from typing import Literal

from pandas import DataFrame
from pydantic import BaseModel, Field

from graphdatascience.graph.graph_api import Graph
from graphdatascience.procedure_surface.api.base_result import MutateResult, NodeResult, StatsResult, WriteResult
from graphdatascience.procedure_surface.api.descriptions import RANDOM_SEED_DESCRIPTION, TASK_NAME_DESCRIPTION
from graphdatascience.procedure_surface.api.job_handle import JobHandle


class PredictEndpoints(ABC):
    @abstractmethod
    def compute(
        self,
        G: Graph,
        *,
        model_name: str,
        random_seed: int | None = None,
        job_id: str | None = None,
        node_labels: list[str] = ["*"],
        relationship_types: list[str] = ["*"],
        feature_properties: list[str],
    ) -> JobHandle:
        """
        Parameters
        ----------
        G
            The graph to run the procedure on.
        model_name
            Name of the previously trained graph encoder + decoder model to use for prediction.
        random_seed
            Seed for random number generation to ensure reproducible results.
        job_id
            Identifier to track the job by. Generated by the server if not specified.
        node_labels
            List of node labels to include in the job configuration.
        relationship_types
            List of relationship types to include in the job configuration.
        feature_properties
            List of features to include in the job configuration.

        Returns
        -------
        JobHandle
        """

    @abstractmethod
    def stream(
        self,
        G: Graph,
        *,
        model_name: str,
        random_seed: int | None = None,
        job_id: str | None = None,
        node_labels: list[str] = ["*"],
        relationship_types: list[str] = ["*"],
        feature_properties: list[str],
    ) -> DataFrame:
        """
        Parameters
        ----------
        G
            The graph to run the procedure on.
        model_name
            Name of the previously trained graph encoder + decoder model to use for prediction.
        random_seed
            Seed for random number generation to ensure reproducible results.
        job_id
            Identifier to track the job by. Generated by the server if not specified.
        node_labels
            List of node labels to include in the job configuration.
        relationship_types
            List of relationship types to include in the job configuration.
        feature_properties
            List of features to include in the job configuration.

        Returns
        -------
        DataFrame
        """

    @abstractmethod
    def mutate(
        self,
        G: Graph,
        *,
        model_name: str,
        random_seed: int | None = None,
        mutate_property: str,
        job_id: str | None = None,
        node_labels: list[str] = ["*"],
        relationship_types: list[str] = ["*"],
        feature_properties: list[str],
    ) -> PredictMutateResult:
        """
        Parameters
        ----------
        G
            The graph to run the procedure on.
        model_name
            Name of the previously trained graph encoder + decoder model to use for prediction.
        random_seed
            Seed for random number generation to ensure reproducible results.
        mutate_property
            Name of the node property to store the result in, on the in-memory graph.
        job_id
            Identifier to track the job by. Generated by the server if not specified.
        node_labels
            List of node labels to include in the job configuration.
        relationship_types
            List of relationship types to include in the job configuration.
        feature_properties
            List of features to include in the job configuration.

        Returns
        -------
        PredictMutateResult
        """

    @abstractmethod
    def stats(
        self,
        G: Graph,
        *,
        model_name: str,
        random_seed: int | None = None,
        job_id: str | None = None,
        node_labels: list[str] = ["*"],
        relationship_types: list[str] = ["*"],
        feature_properties: list[str],
    ) -> PredictStatsResult:
        """
        Parameters
        ----------
        G
            The graph to run the procedure on.
        model_name
            Name of the previously trained graph encoder + decoder model to use for prediction.
        random_seed
            Seed for random number generation to ensure reproducible results.
        job_id
            Identifier to track the job by. Generated by the server if not specified.
        node_labels
            List of node labels to include in the job configuration.
        relationship_types
            List of relationship types to include in the job configuration.
        feature_properties
            List of features to include in the job configuration.

        Returns
        -------
        PredictStatsResult
        """

    @abstractmethod
    def write(
        self,
        G: Graph,
        *,
        model_name: str,
        random_seed: int | None = None,
        write_property: str,
        write_concurrency: int,
        job_id: str | None = None,
        node_labels: list[str] = ["*"],
        relationship_types: list[str] = ["*"],
        feature_properties: list[str],
    ) -> PredictWriteResult:
        """
        Parameters
        ----------
        G
            The graph to run the procedure on.
        model_name
            Name of the previously trained graph encoder + decoder model to use for prediction.
        random_seed
            Seed for random number generation to ensure reproducible results.
        write_property
            Name of the node property to write the result to, in the database.
        write_concurrency
            Number of concurrent nodes to write in the database.
        job_id
            Identifier to track the job by. Generated by the server if not specified.
        node_labels
            List of node labels to include in the job configuration.
        relationship_types
            List of relationship types to include in the job configuration.
        feature_properties
            List of features to include in the job configuration.

        Returns
        -------
        PredictWriteResult
        """


class PredictConfig(BaseModel):
    task_name: Literal["gml_predict"] = Field(
        "gml_predict", validation_alias="taskName", description=TASK_NAME_DESCRIPTION
    )
    model_name: str = Field(
        description="Name of the previously trained graph encoder + decoder model to use for prediction."
    )
    random_seed: int = Field(default_factory=lambda: random.randint(0, 2**32 - 1), description=RANDOM_SEED_DESCRIPTION)


class PredictMutateResult(MutateResult, NodeResult):
    pass


class PredictStatsResult(StatsResult, NodeResult):
    pass


class PredictWriteResult(WriteResult, NodeResult):
    pass
