"""This file was generated by scripts/endpoint_codegen/code_generation.py. Do not edit by hand -- re-run the generating script instead."""

from __future__ import annotations

import random
from abc import ABC, abstractmethod
from typing import Annotated, Literal

from pydantic import BaseModel, Field, PositiveInt

from graphdatascience.graph.graph_api import Graph
from graphdatascience.procedure_surface.api.descriptions import RANDOM_SEED_DESCRIPTION, TASK_NAME_DESCRIPTION
from graphdatascience.procedure_surface.api.embedding.config import (
    DecoderConfig,
    FastRPConfig,
    GBClassifierConfig,
    GraphEncoderConfig,
    GraphSAGEConfig,
    IdentityConfig,
    MLPClassifierConfig,
)
from graphdatascience.procedure_surface.api.job_handle import JobHandle


class TrainEndpoints(ABC):
    @abstractmethod
    def compute(
        self,
        G: Graph,
        *,
        graph_encoder: FastRPConfig | GraphSAGEConfig | IdentityConfig,
        decoder: GBClassifierConfig | MLPClassifierConfig,
        model_save_name: str,
        target_label: str,
        target_property: str,
        num_epochs: int | None = None,
        batch_size: int | None = None,
        num_trials: int = 1,
        random_seed: int | None = None,
        job_id: str | None = None,
        node_labels: list[str] = ["*"],
        relationship_types: list[str] = ["*"],
        feature_properties: list[str],
    ) -> JobHandle:
        """
        Parameters
        ----------
        G
            The graph to run the procedure on.
        graph_encoder
            Configuration for the graph encoder to train (e.g. FastRP, GraphSAGE, or Identity).
        decoder
            Configuration for the decoder to train on top of the graph encoder's embeddings.
        model_save_name
            Name to save the trained graph encoder + decoder model under.
        target_label
            Node label to train on.
        target_property
            Node property to train on.
        num_epochs
            Maximum number of training epochs.
        batch_size
            Number of examples per training batch.
        num_trials
            Number of hyperparameter tuning trials to run.
        random_seed
            Seed for random number generation to ensure reproducible results.
        job_id
            Identifier to track the job by. Generated by the server if not specified.
        node_labels
            List of node labels to include in the job configuration.
        relationship_types
            List of relationship types to include in the job configuration.
        feature_properties
            List of features to include in the job configuration.

        Returns
        -------
        JobHandle
        """

    @abstractmethod
    def __call__(
        self,
        G: Graph,
        *,
        graph_encoder: FastRPConfig | GraphSAGEConfig | IdentityConfig,
        decoder: GBClassifierConfig | MLPClassifierConfig,
        model_save_name: str,
        target_label: str,
        target_property: str,
        num_epochs: int | None = None,
        batch_size: int | None = None,
        num_trials: int = 1,
        random_seed: int | None = None,
        job_id: str | None = None,
        node_labels: list[str] = ["*"],
        relationship_types: list[str] = ["*"],
        feature_properties: list[str],
    ) -> None:
        """
        Parameters
        ----------
        G
            The graph to run the procedure on.
        graph_encoder
            Configuration for the graph encoder to train (e.g. FastRP, GraphSAGE, or Identity).
        decoder
            Configuration for the decoder to train on top of the graph encoder's embeddings.
        model_save_name
            Name to save the trained graph encoder + decoder model under.
        target_label
            Node label to train on.
        target_property
            Node property to train on.
        num_epochs
            Maximum number of training epochs.
        batch_size
            Number of examples per training batch.
        num_trials
            Number of hyperparameter tuning trials to run.
        random_seed
            Seed for random number generation to ensure reproducible results.
        job_id
            Identifier to track the job by. Generated by the server if not specified.
        node_labels
            List of node labels to include in the job configuration.
        relationship_types
            List of relationship types to include in the job configuration.
        feature_properties
            List of features to include in the job configuration.
        """


class TrainConfig(BaseModel):
    task_name: Literal["gml_train"] = Field("gml_train", validation_alias="taskName", description=TASK_NAME_DESCRIPTION)
    graph_encoder: Annotated[GraphEncoderConfig, Field(discriminator="graph_encoder_type")] = Field(
        description="Configuration for the graph encoder to train (e.g. FastRP, GraphSAGE, or Identity)."
    )
    decoder: Annotated[DecoderConfig, Field(discriminator="decoder_type")] = Field(
        description="Configuration for the decoder to train on top of the graph encoder's embeddings."
    )
    model_save_name: str = Field(description="Name to save the trained graph encoder + decoder model under.")
    target_label: str = Field(description="Node label to train on.")
    target_property: str = Field(description="Node property to train on.")
    num_epochs: PositiveInt | None = Field(default=None, description="Maximum number of training epochs.")
    batch_size: PositiveInt | None = Field(default=None, description="Number of examples per training batch.")
    num_trials: PositiveInt = Field(default=1, description="Number of hyperparameter tuning trials to run.")
    random_seed: int = Field(default_factory=lambda: random.randint(0, 2**32 - 1), description=RANDOM_SEED_DESCRIPTION)
