= Load data to a projected graph via graph construction

[TIP]
====
Jupyter Notebook available on https://github.com/neo4j/graph-data-science-client/blob/main/examples/load-data-via-graph-construction.ipynb[Github^]
====

This notebook shows the usage of the `gds.alpha.graph.construct` method
(available only in GDS 2.1+) to build a graph directly in memory.

*NOTE:* If you are using AuraDS, it is currently not possible to write
the projected graph back to Neo4j.

== Setup

We need an environment where Neo4j and GDS are available, for example
AuraDS (which comes with GDS preinstalled) or Neo4j Desktop.

Once the credentials to this environment are available, we can install
the `graphdatascience` package and create the `gds` object.

[source, python]
----
!pip install graphdatascience==1.4
----

[source, python]
----
# Import the client
from graphdatascience import GraphDataScience

# Replace with the actual credentials
AURA_CONNECTION_URI = "neo4j+s://xxxxxxxx.databases.neo4j.io"
AURA_USERNAME = "neo4j"
AURA_PASSWORD = ""

# Configure the client with AuraDS-recommended settings if using AuraDS
gds = GraphDataScience(
    AURA_CONNECTION_URI,
    auth=(AURA_USERNAME, AURA_PASSWORD),
    aura_ds=True
)
----

We also import `pandas` to create a Pandas DataFrame from the original
data source.

[source, python]
----
import pandas as pd
----

== Load the Cora dataset

[source, python]
----
# TODO: use URLs within the client repo when the notebook is added there
CORA_CONTENT = "https://raw.githubusercontent.com/neo4j/graph-data-science/master/test-utils/src/main/resources/cora.content"
CORA_CITES = "https://raw.githubusercontent.com/neo4j/graph-data-science/master/test-utils/src/main/resources/cora.cites"
----

We need to perform an additional preprocessing step to convert the
`subject` field (which is a string in the dataset) into an integer,
because node properties have to be numerical in order to be projected
into a graph.

[source, python]
----
# Using non-consecutive values to show class ordering later on

SUBJECT_TO_ID = {
    "Neural_Networks": 0,
    "Rule_Learning": 1,
    "Reinforcement_Learning": 2,
    "Probabilistic_Methods": 3,
    "Theory": 4,
    "Genetic_Algorithms": 5,
    "Case_Based": 6
}
----

[source, python]
----
# Read each CSV locally as a Pandas DataFrame
content = pd.read_csv(CORA_CONTENT, header=None)
cites = pd.read_csv(CORA_CITES, header=None)
----

[source, python]
----
# Create a new DataFrame with a `nodeId` field, a list of node labels,
# and the additional node properties `subject` and `features`
nodes = pd.DataFrame().assign(
    nodeId=content[0], 
    labels="Paper", 
    subject=content[1].replace(SUBJECT_TO_ID), 
    features=content.iloc[:, 2:].apply(list, axis=1)
)
----

[source, python]
----
# Show the first 5 rows of the new DataFrame
nodes.head()
----

[source, python]
----
# Create a new DataFrame containing the relationships between the nodes.
# To create the equivalent of an undirected graph, we need to add direct
# and inverse relationships.
dir_relationships = pd.DataFrame().assign(
    sourceNodeId=cites[0],
    targetNodeId=cites[1],
    relationshipType="CITES"
)

inv_relationships = pd.DataFrame().assign(
    sourceNodeId=cites[1],
    targetNodeId=cites[0],
    relationshipType="CITES"
)

relationships = pd.concat([dir_relationships, inv_relationships]).drop_duplicates()
----

[source, python]
----
# Show the first 20 rows of the new DataFrame
relationships.head(5)
----

[source, python]
----
# Finally, create the in-memory graph
G = gds.alpha.graph.construct(
    "cora-graph",
    nodes,
    relationships
)
----

[source, python]
----
# Check that the new graph has been created
gds.graph.list()
----

[source, python]
----
# Count the nodes in the graph
G.node_count()
----

[source, python]
----
# Get the value of the "subject" node property for
# each node in the graph, printing only the first 5
gds.graph.streamNodeProperties(G, ["subject"]).head()
----

== Cleanup

[source, python]
----
G.drop()
----