[tox]
requires =
	tox-uv
envlist =
	neo4j{5,6}-standard,
	# Vary Pandas
;	py314-pandas{2}-standard,
	# Use oldest PyArrow
	pyarrow19-standard,
	py3{10, 11, 12, 13, 14}-standard,
	networkx{2,3}-nx,
[testenv]

passenv =
	GDS_SESSION_IMAGE
	NEO4J_DATABASE_IMAGE
	BUILD_ID
	GDS_LICENSE_KEY

	GDS_API_SPEC_FILE
	GITHUB_TOKEN

allowlist_externals =
	ruby
	bash
	rm
dependency_groups =
	test
deps =
	neo4j5: neo4j >= 5.0, < 6.0
	neo4j6: neo4j >= 6.0, < 7.0
	pandas2: pandas >= 2.2.2, < 3.0
	pandas2: numpy >= 2.0
	pyarrow19: pyarrow >= 19.0, < 20.0
	pyarrow20: pyarrow >= 20.0, < 21.0
	pyarrow21: pyarrow >= 21.0, < 22.0
	pyarrow22: pyarrow >= 22.0, < 23.0
	pyarrow23: pyarrow >= 23.0, < 24.0
	networkx2: networkx >= 2.0, < 3.0
	networkx3: networkx >= 3.0, < 4.0
commands =
	standard: pytest -x tests
	ogb: pytest tests --include-enterprise --include-ogb
	rm -rf {envdir}/lib

