# frozen_string_literal: true

source 'https://rubygems.org'

gem 'asciidoctor'
gem 'minitest'
# ostruct left the default gems in Ruby 4.0; rubocop -> json still requires it
gem 'ostruct'
gem 'rubocop', require: false
