= GDS Sessions

A GDS Session is a temporary compute environment for running GDS workloads.
It is a service offered by Neo4j and runs within Neo4j's Aura cloud platform.
A GDS Session reads data from a Neo4j DBMS system through a _remote projection_, then runs computations on the projected graph, and lastly can write back the analytical results using _remote write-back_.

NOTE: GDS Sessions are only available for Neo4j AuraDB Enterprise, and not by default. Contact your account manager to get the features enabled.


== Pre-requisites

To create a GDS Session, you need to have a Neo4j Aura account.
Using your account, you need to create Aura API credentials.
These credentials are a pair of `CLIENT_ID` and `CLIENT_SECRET` that you will use to authenticate with the Aura API.
For how to create these credentials, see the https://neo4j.com/docs/aura/platform/api/authentication/#_creating_credentials[Aura documentation].

Using these credentials, you will first create a `GdsSessions` object, and then use it to create a new GDS Session.

.Creating a GdsSessions object.
[source, python, role=no-test]
----
from graphdatascience.gds_session import GdsSessions, AuraAPICredentials

CLIENT_ID = "my-aura-api-client-id"
CLIENT_SECRET = "my-aura-api-client-secret"

# Create a new GdsSessions object
sessions = GdsSessions(ds_connection=AuraAPICredentials(CLIENT_ID, CLIENT_SECRET))
----

The `GdsSessions` object is the top-level API which allows you three operations:

- `get_or_create`: Create a new GDS Session, or connect to an existing one.
- `list`: List all currently active GDS Sessions.
- `delete`: Delete a GDS Session.


== Creating a GDS Session

To create a GDS Session, you need to provide the following information:

- A session name.
The name must be unique.

- A session size.
The size determines the amount of memory and CPU available to the session.
It also determines the cost of running the session.
Available sizes are listed in xref:gds-session-sizes[].

- A DBMS connection.
This is a `DbmsConnectionInfo` object that contains the URI of an AuraDB instance, a username, and a password.

With these three pieces of information, we are ready to create a GDS Session.

.Creating a GDS Session:
[source, python, role=no-test]
----
from graphdatascience.gds_session import SessionSizes, DbmsConnectionInfo

name = "my-new-session"
size = SessionSizes.by_memory().DEFAULT
db_connection_info = DbmsConnectionInfo("neo4j+s://mydbid.databases.neo4j.io", "my-user", "my-password")

# let's create a GDS session!
gds = sessions.get_or_create(
    session_name=name,
    size=size,
    db_connection=db_connection_info,
)
----

The `get_or_create` method will create a new GDS Session if it does not exist, or connect to an existing one if it does.
If the session size is different from the existing one, an error will be raised.


[[gds-session-sizes]]
=== Session sizes

Session sizes are logical and specified using the `SessionSizes.by_memory()` enum.
Possible values are `DEFAULT`, `XS`, `S`, `SM`, `M`, `ML`, `L`, `XL`, `XXL`, `X3L`, `X4L`, `X5L`.

