import ast
from abc import ABC, abstractmethod
from collections.abc import Sequence
from enum import Enum
from functools import reduce
from types import UnionType
from typing import Annotated, Any, Literal, NamedTuple, Union, get_args, get_origin

from pydantic import BaseModel

from graphdatascience.arrow_client.authenticated_flight_client import AuthenticatedArrowClient
from graphdatascience.graph.graph_api import Graph
from graphdatascience.session.remote_ops.write_protocols import WriteProtocol


def _subscript(name: str, args: list[ast.expr]) -> ast.expr:
    slice_node = args[0] if len(args) == 1 else ast.Tuple(elts=args, ctx=ast.Load())
    return ast.Subscript(value=ast.Name(id=name, ctx=ast.Load()), slice=slice_node, ctx=ast.Load())


def _load(name: str) -> ast.Name:
    return ast.Name(id=name, ctx=ast.Load())


def _self_attr(attr: str, store: bool = False) -> ast.Attribute:
    return ast.Attribute(value=_load("self"), attr=attr, ctx=ast.Store() if store else ast.Load())


def _call(func: ast.expr, args: list[ast.expr] | None = None, keywords: list[ast.keyword] | None = None) -> ast.Call:
    return ast.Call(func=func, args=args or [], keywords=keywords or [])


def _kwarg(name: str | None, value: ast.expr) -> ast.keyword:
    return ast.keyword(arg=name, value=value)


GENERATED_FILE_BANNER = (
    "This file was generated by scripts/endpoint_codegen/code_generation.py. "
    "Do not edit by hand -- re-run the generating script instead."
)

NO_DESCRIPTION = "No description provided."


def _is_tag_field(field_info: Any) -> bool:
    # A Literal with a single option (e.g. a discriminator like `task_name`) is fixed by the
    # model itself, not a real choice, so it has no place in a generated method signature.
    return get_origin(field_info.annotation) is Literal and len(get_args(field_info.annotation)) == 1


GRAPH_PARAM = "G"
GRAPH_PARAM_DESCRIPTION = "The graph to run the procedure on."


class InlinedSource(NamedTuple):
    """A spec module's definitions, plus the imports they need, to inline into a generated module."""

    imports: list[ast.stmt] = []
    body: list[ast.stmt] = []


class Spec(NamedTuple):
    """A procedure's name, config model, per-mode return types, and Arrow endpoint route."""

    name: str
    config_model: type[BaseModel]
    return_types: dict[str, type[Any] | None]
    endpoint: str


def inline_source(source: str, relative_modules: dict[str, str]) -> InlinedSource:
    """Split a spec module into the definitions to inline below a generated class and their imports."""
    imports: list[ast.stmt] = []
    body: list[ast.stmt] = []

    for node in ast.parse(source).body:
        if isinstance(node, ast.ImportFrom) and node.level:
            key = "." * node.level + (node.module or "")
            if key not in relative_modules:
                names = [alias.name for alias in node.names]
                raise ValueError(f"Spec module imports {names} from `{key}`, which has no library copy")
            imports.append(ast.ImportFrom(module=relative_modules[key], names=node.names, level=0))
        elif isinstance(node, (ast.Import, ast.ImportFrom)):
            imports.append(node)
        elif isinstance(node, ast.Assign):
            continue  # generator-only metadata (e.g. the module's own `SPEC` tuple), not part of the library
        elif not (isinstance(node, ast.Expr) and isinstance(node.value, ast.Constant)):
            # anything left that isn't the module docstring is a definition (class/function) to carry over
            body.append(node)

    return InlinedSource(imports, body)


class _ClassGenerator:
    """Shared machinery for turning pydantic config models into method signatures."""

    def __init__(
        self,
        config_model: type[BaseModel],
        module_overrides: dict[str, str | None] | None = None,
        inlined: InlinedSource | None = None,
        base_config: type[BaseModel] | None = None,
        mode_configs: dict[str, type[BaseModel]] | None = None,
    ) -> None:
        self.config_model = config_model
        self.base_config = base_config
        self.mode_configs = mode_configs or {}
        self.module_overrides: dict[str, str | None] = module_overrides or {}
        self.inlined = inlined or InlinedSource()
        self.imports: set[tuple[str, str]] = set()

    def _build_imports(self) -> list[ast.stmt]:
        imports_by_module: dict[str, set[str]] = {}
        for module, name in self.imports:
            imports_by_module.setdefault(module, set()).add(name)

        # `ruff check --fix` merges and sorts these with the inlined module's own imports afterwards.
        return list(self.inlined.imports) + [
            ast.ImportFrom(module=module, names=[ast.alias(name=n) for n in sorted(names)], level=0)
            for module, names in sorted(imports_by_module.items())
        ]

    def _render_module(self, body: list[ast.stmt]) -> str:
        docstring = ast.Expr(value=ast.Constant(value=GENERATED_FILE_BANNER))
        preamble: list[ast.stmt] = []
        if self.inlined.body:
            # The inlined models are defined below the class that annotates itself with them, the
            # same layout the hand-written endpoints use, so those annotations must stay unevaluated.
            preamble.append(ast.ImportFrom(module="__future__", names=[ast.alias(name="annotations")], level=0))

        module_node = ast.Module(
            body=[docstring, *preamble, *self._build_imports(), *body, *self.inlined.body], type_ignores=[]
        )

        # unparse() reads node.lineno while walking FunctionDefs, which a
        # hand-built AST doesn't have unless this runs first.
        ast.fix_missing_locations(module_node)
        return ast.unparse(module_node)

    def _render_annotation(self, tp: Any) -> ast.expr:
        """Build the AST expression for a type, recording the (module, name) of anything it references that needs an import."""
        origin = get_origin(tp)

        if origin is Annotated:
            # Metadata (e.g. a pydantic discriminator `Field(...)`) only matters
            # for validation, not for a client-facing signature, so drop it and
            # keep the actual type.
            return self._render_annotation(get_args(tp)[0])

        if origin is Literal:
            return self._subscript_for(origin, [ast.Constant(value=v) for v in get_args(tp)])

        if origin is not None:
            parts = [self._render_annotation(arg) for arg in get_args(tp)]
            if origin in (Union, UnionType):
                return reduce(lambda left, right: ast.BinOp(left=left, op=ast.BitOr(), right=right), parts)
            return self._subscript_for(origin, parts)

        if tp is type(None):
            return ast.Constant(value=None)

        if isinstance(tp, type):
            self._register_import(tp)
            return ast.Name(id=tp.__name__, ctx=ast.Load())

        return ast.parse(str(tp), mode="eval").body

    def _render_default(self, value: Any) -> ast.expr:
        """Build the AST expression for a static default value, refusing anything that can't round-trip as source."""
        if isinstance(value, Enum):
            self._register_import(type(value))
            return ast.Attribute(
                value=ast.Name(id=type(value).__name__, ctx=ast.Load()), attr=value.name, ctx=ast.Load()
            )

        node = ast.Constant(value=value)
        try:
            renders_back_equal = ast.literal_eval(ast.unparse(node)) == value
        except (ValueError, SyntaxError):
            renders_back_equal = False
        if not renders_back_equal:
            raise TypeError(f"Cannot render default {value!r} of type {type(value).__name__} as source code")
        return node

    def _subscript_for(self, origin: Any, args: list[ast.expr]) -> ast.expr:
        self._register_import(origin)
        return _subscript(origin.__name__, args)

    def _register_import(self, cls: Any) -> None:
        if cls.__module__ == "builtins":
            return
        module = self.module_overrides.get(cls.__module__, cls.__module__)
        if module is not None:  # None: inlined into the module being generated, so nothing to import
            self.imports.add((module, cls.__name__))

    def _symbol(self, obj: Any) -> ast.Name:
        """Reference a class or function by name, registering its import. For value positions (a
        call target), not type-annotation positions -- use `_render_annotation` for those."""
        self._register_import(obj)
        return _load(obj.__name__)

    def _fields(self, model: type[BaseModel] | None) -> list[tuple[str, Any]]:
        """The (name, FieldInfo) pairs of a model that a caller gets to set."""
        if model is None:
            return []
        return [(name, info) for name, info in model.model_fields.items() if not _is_tag_field(info)]

    def _payload_fields(self) -> list[tuple[str, Any]]:
        """Parameters that end up in the job configuration sent to the server."""
        return self._fields(self.config_model) + self._fields(self.base_config)

    def _mode_fields(self, mode: str | None) -> list[tuple[str, Any]]:
        """Parameters a mode hands to the endpoints helper instead of sending as configuration."""
        return self._fields(self.mode_configs.get(mode)) if mode is not None else []

    def _signature_fields(self, mode: str | None) -> list[tuple[str, Any]]:
        # The mode's own parameters sit right after the procedure's, ahead of the boilerplate every
        # mode shares -- and they are the ones most likely to be required, e.g. `mutate_property`.
        return self._fields(self.config_model) + self._mode_fields(mode) + self._fields(self.base_config)

    def _build_signature(self, mode: str | None, return_type: Any) -> tuple[ast.arguments, ast.expr]:
        kw_only_args: list[ast.arg] = []
        kw_defaults: list[ast.expr | None] = []

        for field_name, field_info in self._signature_fields(mode):
            arg, default = self._field_kwonly_arg(field_name, field_info)
            kw_only_args.append(arg)
            kw_defaults.append(default)

        args_node = ast.arguments(
            posonlyargs=[],
            args=[ast.arg(arg="self"), ast.arg(arg=GRAPH_PARAM, annotation=self._render_annotation(Graph))],
            vararg=None,
            kwonlyargs=kw_only_args,
            kw_defaults=kw_defaults,
            kwarg=None,
            defaults=[],
        )
        return args_node, self._render_annotation(return_type)

    def _field_kwonly_arg(self, field_name: str, field_info: Any) -> tuple[ast.arg, ast.expr | None]:
        annotation = self._render_annotation(field_info.annotation)

        if field_info.default_factory is not None:
            # No static value to bake in (e.g. a random seed), so fall back to a
            # `None` sentinel and let the caller supply their own if they want one.
            optional_annotation = ast.BinOp(left=annotation, op=ast.BitOr(), right=ast.Constant(value=None))
            return ast.arg(arg=field_name, annotation=optional_annotation), ast.Constant(value=None)

        arg = ast.arg(arg=field_name, annotation=annotation)
        default = self._render_default(field_info.default) if not field_info.is_required() else None
        return arg, default


class _AbcClassGenerator(_ClassGenerator):
    """Generates an ABC with one @abstractmethod stub per mode."""

    def __init__(
        self,
        config_model: type[BaseModel],
        module_overrides: dict[str, str | None] | None = None,
        inlined: InlinedSource | None = None,
        base_config: type[BaseModel] | None = None,
        mode_configs: dict[str, type[BaseModel]] | None = None,
    ) -> None:
        super().__init__(config_model, module_overrides, inlined, base_config, mode_configs)
        self._register_import(ABC)
        self._register_import(abstractmethod)

    def generate(self, class_name: str, return_types: dict[str, type[Any] | None]) -> str:
        method_nodes: list[ast.stmt] = [
            self._build_method(name, return_type) for name, return_type in return_types.items()
        ]

        class_node = ast.ClassDef(
            name=class_name,
            bases=[ast.Name(id=ABC.__name__, ctx=ast.Load())],
            keywords=[],
            body=method_nodes,
            decorator_list=[],
            type_params=[],
        )
        return self._render_module([class_node])

    def _build_method(self, method_name: str, return_type: type[Any] | None) -> ast.FunctionDef:
        args_node, returns = self._build_signature(method_name, return_type)
        docstring = self._build_docstring(method_name, return_type)
        return ast.FunctionDef(
            name=method_name,
            args=args_node,
            body=[ast.Expr(value=ast.Constant(value=docstring))],
            decorator_list=[ast.Name(id=abstractmethod.__name__, ctx=ast.Load())],
            returns=returns,
            type_params=[],
        )

    def _build_docstring(self, method_name: str, return_type: type[Any] | None) -> str:
        lines = ["Parameters", "----------", GRAPH_PARAM, f"    {GRAPH_PARAM_DESCRIPTION}"]
        for field_name, field_info in self._signature_fields(method_name):
            lines += [field_name, f"    {field_info.description or NO_DESCRIPTION}"]

        if return_type is not None:
            lines += ["", "Returns", "-------", getattr(return_type, "__name__", str(return_type))]

        # ast.unparse() doesn't reindent embedded newlines in a string constant, so the
        # docstring body has to carry its own indentation to line up under the method body.
        # This generator only ever nests methods one level inside a top-level class, and
        # ast.unparse() always uses 4-space indents, so that's a fixed 8 spaces.
        indent = " " * 8
        body = "\n".join(f"{indent}{line}" if line else "" for line in lines)
        return f"\n{body}\n{indent}"


class _ArrowClassGenerator(_ClassGenerator):
    """
    Generates an Arrow implementation of a generated entrypoints ABC. Every method builds a
    config object from its parameters, runs it via the given endpoints helper class, and wraps
    the result according to a fixed vocabulary of modes: compute, stream, stats, mutate, write,
    __call__.
    """

    def __init__(
        self,
        config_model: type[BaseModel],
        entrypoints_module: str,
        entrypoints_class_name: str,
        endpoint: str,
        endpoints_helper_class: type[Any],
        module_overrides: dict[str, str | None] | None = None,
        base_config: type[BaseModel] | None = None,
        mode_configs: dict[str, type[BaseModel]] | None = None,
    ) -> None:
        super().__init__(config_model, module_overrides, None, base_config, mode_configs)
        self.entrypoints_class_name = entrypoints_class_name
        self.endpoint = endpoint
        self.endpoints_helper_class = endpoints_helper_class
        self.imports.add((entrypoints_module, entrypoints_class_name))

    def generate(self, class_name: str, return_types: dict[str, type[Any] | None]) -> str:
        method_nodes = [self._build_method(name, return_type) for name, return_type in return_types.items()]

        class_node = ast.ClassDef(
            name=class_name,
            bases=[ast.Name(id=self.entrypoints_class_name, ctx=ast.Load())],
            keywords=[],
            body=[self._build_init(), *method_nodes, self._build_config_method()],
            decorator_list=[],
            type_params=[],
        )
        return self._render_module([class_node])

    def _build_init(self) -> ast.FunctionDef:
        args_node = ast.arguments(
            posonlyargs=[],
            args=[
                ast.arg(arg="self"),
                ast.arg(arg="arrow_client", annotation=self._render_annotation(AuthenticatedArrowClient)),
                ast.arg(arg="write_protocol", annotation=self._render_annotation(WriteProtocol | None)),
                ast.arg(arg="show_progress", annotation=self._render_annotation(bool)),
            ],
            vararg=None,
            kwonlyargs=[],
            kw_defaults=[],
            kwarg=None,
            defaults=[ast.Constant(value=None), ast.Constant(value=True)],
        )
        body: list[ast.stmt] = [
            ast.Assign(targets=[_self_attr("_arrow_client", store=True)], value=_load("arrow_client")),
            ast.Assign(
                targets=[_self_attr("_endpoints_helper", store=True)],
                value=_call(
                    self._symbol(self.endpoints_helper_class),
                    args=[_load("arrow_client"), _load("write_protocol"), _load("show_progress")],
                ),
            ),
        ]
        return ast.FunctionDef(
            name="__init__",
            args=args_node,
            body=body,
            decorator_list=[],
            returns=ast.Constant(value=None),
            type_params=[],
        )

    def _build_config_method(self) -> ast.FunctionDef:
        args_node, returns = self._build_signature(None, dict[str, Any])

        body, config_dump = self._model_dump(self.config_model, self._fields(self.config_model), [])

        if self.base_config is None:
            body.append(ast.Return(value=config_dump))
        else:
            body.append(ast.Assign(targets=[ast.Name(id="config", ctx=ast.Store())], value=config_dump))
            base_body, base_dump = self._model_dump(self.base_config, self._fields(self.base_config), [], "base_kwargs")
            body += base_body
            body.append(
                ast.Expr(
                    value=_call(ast.Attribute(value=_load("config"), attr="update", ctx=ast.Load()), args=[base_dump])
                )
            )
            body.append(ast.Return(value=_load("config")))

        return ast.FunctionDef(
            name="_build_config", args=args_node, body=body, decorator_list=[], returns=returns, type_params=[]
        )

    def _model_dump(
        self,
        model: type[BaseModel],
        fields: list[tuple[str, Any]],
        extra_keywords: list[ast.keyword],
        kwargs_var: str = "extra_kwargs",
    ) -> tuple[list[ast.stmt], ast.expr]:
        """Build `Model(...).model_dump(exclude_none=True)`, plus the statements it needs beforehand."""
        factory_fields = [name for name, info in fields if info.default_factory is not None]
        keywords = extra_keywords + [_kwarg(name, _load(name)) for name, info in fields if info.default_factory is None]

        body: list[ast.stmt] = []
        if factory_fields:
            # A field with a default_factory takes a `None` sentinel in the signature, so it has to be
            # left out of the call entirely for the factory to run.
            body.append(
                ast.AnnAssign(
                    target=ast.Name(id=kwargs_var, ctx=ast.Store()),
                    annotation=self._render_annotation(dict[str, Any]),
                    value=ast.Dict(keys=[], values=[]),
                    simple=1,
                )
            )
            for name in factory_fields:
                body.append(
                    ast.If(
                        test=ast.Compare(left=_load(name), ops=[ast.IsNot()], comparators=[ast.Constant(value=None)]),
                        body=[
                            ast.Assign(
                                targets=[
                                    ast.Subscript(
                                        value=_load(kwargs_var), slice=ast.Constant(value=name), ctx=ast.Store()
                                    )
                                ],
                                value=_load(name),
                            )
                        ],
                        orelse=[],
                    )
                )
            keywords.append(_kwarg(None, _load(kwargs_var)))

        dump_call = _call(
            ast.Attribute(
                value=_call(self._symbol(model), keywords=keywords),
                attr=BaseModel.model_dump.__name__,
                ctx=ast.Load(),
            ),
            keywords=[_kwarg("exclude_none", ast.Constant(value=True))],
        )
        return body, dump_call

    def _build_method(self, method_name: str, return_type: type[Any] | None) -> ast.FunctionDef:
        args_node, returns = self._build_signature(method_name, return_type)
        return ast.FunctionDef(
            name=method_name,
            args=args_node,
            body=self._build_method_body(method_name, return_type),
            decorator_list=[],
            returns=returns,
            type_params=[],
        )

    def _build_method_body(self, method_name: str, return_type: type[Any] | None) -> list[ast.stmt]:
        config_call = _call(
            _self_attr("_build_config"),
            args=[_load(GRAPH_PARAM)],
            keywords=[_kwarg(name, _load(name)) for name, _ in self._payload_fields()],
        )
        body: list[ast.stmt] = [ast.Assign(targets=[ast.Name(id="config", ctx=ast.Store())], value=config_call)]

        helper = self.endpoints_helper_class
        endpoint_arg = ast.Constant(value=self.endpoint)
        mode_args = [_load(name) for name, _ in self._mode_fields(method_name)]

        if method_name == "compute":
            # Like the hand-written endpoints, `compute` hands back the running job instead of
            # waiting for it, so there is no summary to wrap in a result type.
            call = self._helper_call(helper.run_job.__name__, [_load(GRAPH_PARAM), endpoint_arg, _load("config")])
            body.append(ast.Return(value=call))
        elif method_name == "stream":
            call = self._helper_call(
                helper.run_job_and_stream.__name__, [endpoint_arg, _load(GRAPH_PARAM), _load("config")]
            )
            body.append(ast.Return(value=call))
        elif method_name == "mutate":
            assert return_type is not None
            self._require_mode_args(method_name, mode_args)
            call = self._helper_call(helper.run_job_and_mutate.__name__, [endpoint_arg, _load("config"), *mode_args])
            body.append(ast.Assign(targets=[ast.Name(id="result", ctx=ast.Store())], value=call))
            body.append(ast.Return(value=_call(self._symbol(return_type), keywords=[_kwarg(None, _load("result"))])))
        elif method_name == "stats":
            assert return_type is not None
            call = self._helper_call(helper.run_job_and_get_summary.__name__, [endpoint_arg, _load("config")])
            body.append(ast.Assign(targets=[ast.Name(id="result", ctx=ast.Store())], value=call))
            body.append(ast.Return(value=_call(self._symbol(return_type), keywords=[_kwarg(None, _load("result"))])))
        elif method_name == "write":
            assert return_type is not None
            self._require_mode_args(method_name, mode_args)
            call = self._helper_call(
                helper.run_job_and_write.__name__,
                [endpoint_arg, _load(GRAPH_PARAM), _load("config"), *mode_args],
            )
            body.append(ast.Assign(targets=[ast.Name(id="result", ctx=ast.Store())], value=call))
            body.append(ast.Return(value=_call(self._symbol(return_type), keywords=[_kwarg(None, _load("result"))])))
        elif method_name == "__call__":
            call = self._helper_call(helper.run_job_and_get_summary.__name__, [endpoint_arg, _load("config")])
            body.append(ast.Expr(value=call))
            body.append(ast.Return(value=ast.Constant(value=None)))
        else:
            raise ValueError(f"Unsupported method for arrow generation: {method_name}")

        return body

    def _require_mode_args(self, method_name: str, mode_args: Sequence[ast.expr]) -> None:
        if not mode_args:
            raise ValueError(
                f"Mode `{method_name}` needs a config in `mode_configs` declaring the parameters "
                f"{self.endpoints_helper_class.__name__} takes for it, e.g. the property to write to."
            )

    def _helper_call(self, method_name: str, args: list[ast.expr]) -> ast.Call:
        return _call(ast.Attribute(value=_self_attr("_endpoints_helper"), attr=method_name, ctx=ast.Load()), args=args)


def generate_client_class(
    config_model: type[BaseModel],
    class_name: str,
    return_types: dict[str, type[Any] | None],
    module_overrides: dict[str, str | None] | None = None,
    inlined: InlinedSource | None = None,
    base_config: type[BaseModel] | None = None,
    mode_configs: dict[str, type[BaseModel]] | None = None,
) -> str:
    return _AbcClassGenerator(config_model, module_overrides, inlined, base_config, mode_configs).generate(
        class_name, return_types
    )


def generate_arrow_client_class(
    config_model: type[BaseModel],
    class_name: str,
    entrypoints_module: str,
    entrypoints_class_name: str,
    endpoint: str,
    return_types: dict[str, type[Any] | None],
    endpoints_helper_class: type[Any],
    module_overrides: dict[str, str | None] | None = None,
    base_config: type[BaseModel] | None = None,
    mode_configs: dict[str, type[BaseModel]] | None = None,
) -> str:
    return _ArrowClassGenerator(
        config_model,
        entrypoints_module,
        entrypoints_class_name,
        endpoint,
        endpoints_helper_class,
        module_overrides,
        base_config,
        mode_configs,
    ).generate(class_name, return_types)
