"""This file was generated by scripts/endpoint_codegen/code_generation.py. Do not edit by hand -- re-run the generating script instead."""

TASK_NAME_DESCRIPTION = "Discriminator identifying which task the backend should run; not settable by the client."
RANDOM_SEED_DESCRIPTION = "Seed for random number generation to ensure reproducible results."
GRAPH_NAME_DESCRIPTION = "Name of the projected graph to run the procedure on."
