"""This file was generated by scripts/endpoint_codegen/code_generation.py. Do not edit by hand -- re-run the generating script instead."""

from pydantic import BaseModel, Field

# Parameters that are not specific to one procedure: those every mode accepts, and those a given
# mode needs on top of the procedure's own config. Specs name them per mode instead of the generator
# hard-coding a parameter list, so a new procedure declares its modes rather than editing the generator.


class BaseJobConfig(BaseModel):
    """Accepted by every mode, and sent as part of the job configuration."""

    # concurrency: int | None = Field(
    #     default=None, description="Number of concurrent threads to run the job with. Server default if not specified."
    # )
    job_id: str | None = Field(
        default=None, description="Identifier to track the job by. Generated by the server if not specified."
    )
    # log_progress: bool = Field(default=True, description="Whether the job should report its progress to the log.")
    node_labels: list[str] = Field(
        default=["*"], description="List of node labels to include in the job configuration."
    )
    relationship_types: list[str] = Field(
        default=["*"], description="List of relationship types to include in the job configuration."
    )
    feature_properties: list[str] = Field(description="List of features to include in the job configuration.")


class MutateNodePropertyConfig(BaseModel):
    """Accepted by the `mutate` mode, and passed to the endpoints helper rather than sent as config."""

    mutate_property: str = Field(
        description="Name of the node property to store the result in, on the in-memory graph."
    )


class WriteNodePropertyConfig(BaseModel):
    """Accepted by the `write` mode, and passed to the endpoints helper rather than sent as config."""

    write_property: str = Field(description="Name of the node property to write the result to, in the database.")
    write_concurrency: int = Field(description="Number of concurrent nodes to write in the database.")
