#!/usr/bin/env bash

set -o errexit
set -o nounset
set -o pipefail

echo "Checking ruff"
uv run ruff check .
uv run ruff format --check .
echo "Checking mypy"
uv run mypy .



if [ "${SKIP_NOTEBOOKS:-false}" == "true" ]; then
  echo "Skipping notebooks"
  exit 0
fi

echo "Checking notebooks"
. scripts/parallel_jobs.sh

PYTHON="$(uv run python -c 'import sys; print(sys.executable)')"
NOTEBOOKS=(./examples/*.ipynb) # ./examples/dev/*.ipynb

check_notebook() {
  local file="$1"
  local original formatted
  original="$(cat "$file")"
  formatted="$("$PYTHON" scripts/clean_notebooks.py -i "$file" -o stdout)"

  if [[ "$formatted" != "$original" ]];
  then
    echo "Notebook $file is not correctly formatted. See diff above for more details."
    diff --color=always --suppress-common-lines --minimal --side-by-side <(echo "$original") <(echo "$formatted")
    return 1
  fi
}

for f in "${NOTEBOOKS[@]}"
do
  spawn check_notebook "$f"
done
wait_jobs
