#!/usr/bin/env bash

set -o errexit
set -o nounset
set -o pipefail

python -m ruff check .
python -m ruff format --check .

if [ "${SKIP_NOTEBOOKS:-false}" == "true" ]; then
  echo "Skipping notebooks"
  exit 0
fi

echo "Checking notebooks"
NOTEBOOKS="./examples/*.ipynb" # ./examples/dev/*.ipynb"
for f in $NOTEBOOKS
do
  NB=$(cat $f)
  FORMATTED_NB=$(python -m jupyter nbconvert \
    --clear-output \
    --stdout \
    --ClearOutputPreprocessor.enabled=True \
    --ClearMetadataPreprocessor.enabled=True \
    --ClearMetadataPreprocessor.preserve_cell_metadata_mask='tags' \
    --log-level CRITICAL \
    $f)

  if [[ "$FORMATTED_NB" != "$NB" ]];
  then
    echo "Notebook $f is not correctly formatted. See diff above for more details."
    diff --color=always --suppress-common-lines --minimal --side-by-side <(echo "$NB") <(echo "$FORMATTED_NB")
    exit 1
  fi
done
