#!/usr/bin/env bash

set -o errexit
set -o nounset
set -o pipefail
set -o xtrace

python -m ruff check . --fix
python -m ruff format .

if [ "${SKIP_NOTEBOOKS:-false}" == "true" ]; then
  echo "Skipping notebooks"
  exit 0
fi

python scripts/clean_notebooks.py -i examples/ -o inplace
