#!/usr/bin/env bash

set -o errexit
set -o nounset
set -o pipefail
set -o xtrace

python -m ruff check . --fix
python -m ruff format .
python -m jupyter nbconvert \
  --clear-output \
  --inplace \
  --ClearOutputPreprocessor.enabled=True \
  --ClearMetadataPreprocessor.enabled=True \
    --ClearMetadataPreprocessor.preserve_cell_metadata_mask='tags' \
  --log-level CRITICAL \
  ./examples/*.ipynb \
  ./examples/dev/*.ipynb
