#!/bin/bash

set -o errexit
set -o nounset
set -o pipefail

for file in examples/*; do
    # Temporarily skipping notebooks requiring next server version
    if test -f "$file" && test "$file" != "examples/kge-predict-transe-pyg-train.ipynb"; then
        echo "Executing jupyter notebook $file"
        jupyter nbconvert --to notebook --inplace --execute --ExecutePreprocessor.kernel_name=python3 $file
        echo "Finished executing jupyter notebook $file"
    fi
done

