= Run graph algorithms

include::ROOT:partial$/gds-object.adoc[]


== Introduction

Running most algorithms with the Python client is structurally similar to using the Cypher API:

include::ROOT:partial$/algorithm-syntax.adoc[]

Here we can note a few key differences:

* Instead of camelCase, we use snake_case, such as `gds.page_rank.stream` instead of `gds.pageRank.stream`.
* Instead of a graph name string as first argument, we have a xref:graph-object.adoc[graph object] as first positional argument.
* Instead of a configuration map, we have explicit positional and keyword arguments.

The result of running a procedure is returned as either a pandas `DataFrame` or a typed pydantic object depending on the xref:algorithms.adoc#algorithms-execution-mode[execution mode].

To exemplify this, we introduce a small road-network graph:

[source,python,group=algo]
----
gds.run_cypher(
  """
  CREATE
    (a:City {name: "New York City", settled: 1624}),
    (b:City {name: "Philadelphia", settled: 1682}),
    (c:City:Capital {name: "Washington D.C.", settled: 1790}),
    (d:City {name: "Baltimore"}),
    (e:City {name: "Atlantic City"}),
    (f:City {name: "Boston"}),

    (a)-[:ROAD {cost: 50}]->(b),
    (a)-[:ROAD {cost: 50}]->(c),
    (a)-[:ROAD {cost: 100}]->(d),
    (b)-[:ROAD {cost: 40}]->(d),
    (c)-[:ROAD {cost: 40}]->(d),
    (c)-[:ROAD {cost: 80}]->(e),
    (d)-[:ROAD {cost: 30}]->(e),
    (d)-[:ROAD {cost: 80}]->(f),
    (e)-[:ROAD {cost: 40}]->(f);
  """
)
G, project_result = gds.graph.project.native("road_graph", "City", "ROAD", relationship_properties=["cost"])

assert G.relationship_count() == 9
----


Now we are ready to run algorithms on our graph `G`.

[source,python,group=algo]
----
louvain_result = gds.louvain.mutate(
    G,                            #  Graph object
    max_iterations=5,             #  Configuration parameters
    mutate_property="community"
)
assert louvain_result.community_count > 0

fastrp_result = gds.fast_rp.write(
    G,                                  #  Graph object
    feature_properties=["community"],   #  Configuration parameters
    embedding_dimension=256,
    property_ratio=0.3,
    relationship_weight_property="cost",
    write_property="embedding"
)
assert fastrp_result.node_properties_written == G.node_count()
----

Some algorithms deviate from the standard syntactic structure.
We describe how to use them in the Python client in the sections below.


[[algorithms-execution-mode]]
== Execution modes

Algorithms return results in a format that is controlled by its execution mode.
These modes are explained in some detail in link:{gds-docs-base-uri}/common-usage/running-algos/[Running algorithms].
In the Python client, the `stats`, `mutate` and `write` modes return a typed pydantic object such as link:{gds-api-uri}/endpoints/centrality_endpoints/#graphdatascience.procedure_surface.api.centrality.PageRankMutateResult[`PageRankMutateResult`].


=== Stream

The `stream` mode is a bit different as this mode does not retain the result in any form on the server side.
Instead, the result is streamed back to the Python client, as a pandas `DataFrame`.
The result is materialized on the client side immediately once the computation is finished.
Streaming results back in this way can be resource-intensive, as the result can be large.
Typically, the result size will be in the same order of magnitude as the graph.
Some algorithms produce particularly sizeable results, for example node embeddings.


=== Train

The `train` mode is used for algorithms that produce a machine learning model into the link:{gds-docs-base-uri}/model-catalog/[GDS Model Catalog].
The Python client has special support for working with such models, which we describe in xref:model-object.adoc[The model object].


== Algorithms that require node matching

Some algorithms take (database) node ids as inputs.
These node ids must be matched directly from the Neo4j database.
This is straight-forward when working in Cypher.
In the Python client there is a convenience method link:{gds-api-uri}/endpoints/util_endpoints/#graphdatascience.procedure_surface.api.util_endpoints.UtilEndpoints.find_node_id[`gds.util.find_node_id`] to retrieve a node id based on node labels and property key-value pairs.

For example, to find a source and target node of a graph `G` with cities to run link:link:{gds-docs-base-uri}/algorithms/dijkstra-source-target/[Dijkstra Source-Target Shortest Path] on, we could do the following:

[source,python,group=algo]
----
source_id = gds.util.find_node_id(["City"], {"name": "New York City"})
target_id = gds.util.find_node_id(["City"], {"name": "Boston"})

result = gds.shortest_path.dijkstra.stream(
    G,
    source_node=source_id,
    target_nodes=target_id,
    relationship_weight_property="cost"
)
assert result["totalCost"][0] == 160
----

`gds.util.find_node_id` takes a list of node labels and a dictionary of node property key-value pairs.
The nodes found are those that have all labels specified and fully match all property key-value pairs given.
Note that exactly one node per method call must be matched, otherwise an error will be raised.


=== Cypher mapping

The Python call:

[source,python,group=algo]
----
gds.util.find_node_id(labels=["City", "Capital"], properties={"settled": 1790, "name": "Washington D.C."})
----

is exactly equivalent to the Cypher statement:

[source,cypher]
----
MATCH (n:City:Capital {settled: 1790, name: 'Washington D.C.'})
RETURN id(n) AS id
----

To do more advanced matching beyond the capabilities of `find_node_id()` we recommend using Cypher's `MATCH` via `gds.run_cypher`.


== Topological link prediction

The methods for doing link:{gds-docs-base-uri}/algorithms/linkprediction/[Topological link prediction] are a bit different.
Just like in the GDS procedure API they do not take a graph as an argument, but rather two node references as positional arguments.
And they simply return the similarity score of the prediction just made as a float - not any kind of pandas data structure.

For example, to run the Adamic Adar algorithm, we can use the following:

[source,python,group=algo]
----
node1 = gds.util.find_node_id(["City"], {"name": "Boston"})
node2 = gds.util.find_node_id(["City"], {"name": "Atlantic City"})

score = gds.topological_link_prediction.adamic_adar(node1, node2)
assert round(score, 2) == 0.62
----
