= Overview
:description: This manual documents how to use the dedicated Python Client v{docs-version} for the Neo4j Graph Data Science library.

The Neo4j Graph Data Science Python client is the official Neo4j Python library to run algorithms and machine learning pipelines on graphs.
The library wraps the https://neo4j.com/docs/python-manual/current/[Neo4j Python driver] to offer a Python interface to the link:{gds-docs-base-uri}[Neo4j Graph Data Science] (GDS) Cypher API.

You can use the client-specific graph, model, and pipeline objects form a Python program to:

* Create and manage graph projections.
* Run graph algorithms.
* Train and use machine learning pipelines.

For more details on how the Python client objects and functions map to the Cypher API, see the xref:cypher-mapping.adoc[] page.

== Development

The source code of the Python client is available on https://github.com/neo4j/graph-data-science-client[GitHub].

If you have any suggestions or want to report a problem, you can create a https://github.com/neo4j/graph-data-science-client/issues/new[new issue].

// Make this depending on the backend if PDF needs to be generated
(C) {copyright}

License: link:{common-license-page-uri}[Creative Commons 4.0]
