= Installation

To install the latest version of the Python client, run:

[source,console]
----
pip install graphdatascience
----

[[python-client-system-requirements]]
== Requirements

* Check that client supports your Python environments.
+
[opts="header,autowidth", cols="m,m"]
|===
| GDS Python Client | Python environment
| 2.0
| >= 3.10, < 3.15

| 1.22
| >= 3.10, < 3.15
|===

* If you are running the link:{gds-docs-base-uri}[GDS library] locally or on a self-managed server, the Python client must support the GDS version.
*Aura Graph Analytics sessions always run on the latest GDS version.*
+
[opts="header,autowidth", cols="m,m"]
|===
| GDS Python Client | GDS version
| 2.0
| >= 2.13, < 2.28, < 2026.8

| 1.22
| >= 2.6, < 2.28, < 2026.6
|===

* If the link:https://neo4j.com/docs/python-manual/current/[Neo4j Python driver] is already installed on your system, make sure its version is compatible with the GDS Python client.
+
[opts="header,autowidth", cols="m,m"]
|===
| GDS Python Client | Neo4j Python Driver version
| 2.0
| >= 5.26.0, < 7.0.0

| 1.22
| >= 4.4.12, < 7.0.0
|===

== Optional dependencies

=== NetworkX graphs

Install the optional `networkx` dependency if you plan to load xref:graph-object#networkx[NetworkX graphs]:

[source,console]
----
pip install "graphdatascience[networkx]"
----

=== OGB dataset

Install the optional `ogb` dependency if you plan to use the xref:common-datasets#ogb[OGB dataset]:

[source,console]
----
pip install "graphdatascience[ogb]"
----

=== Neo4j Python driver speedup extension

The `graphdatascience` library uses the Neo4j Python driver under the hood to communicate with Neo4j DBMSs.
To use the link:https://github.com/neo4j/neo4j-python-driver-rust-ext[Rust extension] for better performance, you must install the optional `rust_ext` dependency:

[source,console]
----
pip install "graphdatascience[rust_ext]"
----

Depending on your system, you may need additional installation steps.
See the https://github.com/neo4j/neo4j-python-driver-rust-ext?tab=readme-ov-file#requirements[Rust extension README] for more details.
