= Installation

The Neo4j Graph Data Science Python client is available as the `graphdatascience` package link:https://pypi.org/project/graphdatascience/[on PyPI].

Use `pip` to install the latest released version:

[source,bash]
----
pip install graphdatascience
----

[[python-client-system-requirements]]
== Requirements

The Python client requires the Neo4j Graph Data Science (GDS) library to be available on a link:{gds-docs-base-uri}/installation[server] or in a link:{aura-docs-base-uri}/graph-analytics[cloud environment].

The compatibility table shows compatibility among different versions of the GDS library, the Python interpreter, and the Neo4j Python Driver.

[opts=header, cols="m,m,m,m"]
|===
| Python client | GDS version  | Python version | Neo4j Python Driver version
.1+<.^| 1.20
.1+<.^| >= 2.6, < 2.27
.1+<.^| >= 3.10, < 3.14
.1+<.^| >= 4.4.12, < 7.0.0

.1+<.^| 1.19
.1+<.^| >= 2.6, < 2.25
.1+<.^| >= 3.10, < 3.14
.1+<.^| >= 4.4.12, < 7.0.0

.1+<.^| 1.18
.1+<.^| >= 2.6, < 2.24
.1+<.^| >= 3.10, < 3.14
.1+<.^| >= 4.4.12, < 7.0.0

.1+<.^| 1.17
.1+<.^| >= 2.6, < 2.21
.5+<.^| >= 3.9, < 3.13
.7+<.^| >= 4.4.12, < 6.0.0

.1+<.^| 1.16
.1+<.^| >= 2.6, < 2.19

.1+<.^| 1.15
.1+<.^| >= 2.6, < 2.18

.1+<.^| 1.14
.1+<.^| >= 2.6, < 2.14

.1+<.^| 1.13
.1+<.^| >= 2.6, < 2.14

.1+<.^| 1.12
.1+<.^| >= 2.6, < 2.11
.3+<.^| >= 3.8, < 3.13

.1+<.^| 1.11
.1+<.^| >= 2.6, < 2.10

.1+<.^| 1.10
.1+<.^| >= 2.4, < 2.7
.7+<.^| >= 4.4.2, < 6.0.0

.1+<.^| 1.9
.2+<.^| >= 2.4, < 2.6
.2+<.^| >= 3.8, < 3.12

.1+<.^| 1.8

.1+<.^| 1.7
.1+<.^| >= 2.3, < 2.5
.1+<.^| >= 3.7, < 3.12

.1+<.^| 1.6
.1+<.^| >= 2.2, < 2.4
.3+<.^| >= 3.7, < 3.11

.1+<.^| 1.5
.1+<.^| 2.2

.1+<.^| 1.4
.1+<.^| >= 2.1, < 2.3

.1+<.^| 1.3
.1+<.^| 2.1
.1+<.^| >= 3.7, < 3.10
.4+<.^| >= 4.4.2, < 5.0.0

.1+<.^| 1.2.0
.2+<.^| >= 2.0, < 2.2
.3+<.^| >= 3.6, < 3.10

.1+<.^| 1.1.0
.1+<.^| 1.0.0
.1+<.^| 2.0
|===


== Versioning

The package releases follow link:https://semver.org/[semantic versioning].

Running `pip install --upgrade graphdatascience` will update the package to support all the link:{gds-docs-base-uri}/installation/supported-neo4j-versions/[currently supported GDS library versions], starting with 2.0.


== Optional dependencies

Some features of the Python client require extra dependencies, which are not installed by default as they are either targeted to specific use cases or may require additional setup.

=== Neo4j Python driver speedup extension

The `graphdatascience` package uses the Neo4j Python driver to communicate with a Neo4j database.
The link:https://github.com/neo4j/neo4j-python-driver-rust-ext[Neo4j Python driver Rust extension] can provide a driver speedup, and you can install it with the `rust_ext` dependency:

[source,bash]
----
pip install "graphdatascience[rust_ext]"
----

Depending on your system, additional steps may be required.
See the link:https://github.com/neo4j/neo4j-python-driver-rust-ext?tab=readme-ov-file#requirements[Rust extension README] for more details.


=== OGB dataset loading

Install the optional `ogb` dependency to use the xref:common-datasets#ogb[OGB dataset loader]:

[source,bash]
----
pip install "graphdatascience[ogb]"
----


=== NetworkX graph loading

Install the `networkx` dependency to use the xref:graph-object#networkx[NetworkX graph loader]:

[source,bash]
----
pip install "graphdatascience[networkx]"
----
