= Installation

To install the latest deployed version of the Python client, run:

[source,console]
----
pip install graphdatascience
----

[[python-client-system-requirements]]
== Requirements

The Python client version to install depends on the server-side installation of the link:{gds-docs-base-uri}[GDS library], the Python environment, and the Neo4j Python Driver.

.Python environment
[opts=header, cols="m,m"]
|===
| GDS Python client | Python environment
.1+<.^| 2.0
.1+<.^| >= 3.10, < 3.15

.1+<.^| 1.22
.1+<.^| >= 3.10, < 3.15
|===

.GDS version
[opts=header, cols="m,m"]
|===
| Python Client | GDS version
.1+<.^| 2.0
.1+<.^| >= 2.13, < 2.28, < 2026.7

.1+<.^| 1.22
.1+<.^| >= 2.6, < 2.28, < 2026.6
|===

.Neo4j Python Driver version
[opts=header, cols="m,m"]
|===
| Python Client | Neo4j Python Driver version
.1+<.^| 2.0
.1+<.^| >= 5.26.0, < 7.0.0

.1+<.^| 1.22
.1+<.^| >= 4.4.12, < 7.0.0
|===

== Optional dependencies

=== NetworkX graphs

Install the optional `networkx` dependency if you plan to load xref:graph-object#networkx[NetworkX graphs]:

[source,console]
----
pip install "graphdatascience[networkx]"
----

=== OGB dataset

Install the optional `ogb` dependency if you plan to use the xref:common-datasets#ogb[OGB dataset]:

[source,console]
----
pip install "graphdatascience[ogb]"
----

=== Neo4j Python driver speedup extension

The `graphdatascience` library uses the Neo4j Python driver under the hood to communicate with Neo4j DBMSs.
To use the link:https://github.com/neo4j/neo4j-python-driver-rust-ext[Rust extension] for better performance, you must install the optional `rust_ext` dependency:

[source,console]
----
pip install "graphdatascience[rust_ext]"
----

Depending on your system, you may need additional installation steps.
See the https://github.com/neo4j/neo4j-python-driver-rust-ext?tab=readme-ov-file#requirements[Rust extension README] for more details.
