= Read from a graph

The data in a graph can be read in several ways.

[[graph-object-streaming-properties]]
== Read node and relationship properties

The methods to read node and relationship properties from a graph are the same as in the Cypher API.

Assuming the `GraphDataScience` object is called `gds`:

* link:{gds-docs-base-uri}/management-ops/graph-reads/graph-stream-nodes/[`gds.graph.node_property.stream`] (previously `gds.graph.streamNodeProperty`) returns a single node property
* link:{gds-docs-base-uri}/management-ops/graph-reads/graph-stream-nodes/[`gds.graph.node_properties.stream`] (previously `gds.graph.streamNodeProperties`) returns multiple node properties
* link:{gds-docs-base-uri}/management-ops/graph-reads/graph-stream-relationships/[`gds.graph.relationship_property.stream`] (previously `gds.graph.streamRelationshipProperty`) returns a single relationship property
* link:{gds-docs-base-uri}/management-ops/graph-reads/graph-stream-relationships/[`gds.graph.relationship_properties.stream`] (previously `gds.graph.streamRelationshipProperties`) returns multiple relationship properties

[NOTE]
====
Before version 2.0, the `node_properties.stream` and `relationship_properties.stream` methods included an additional `separate_property_columns` keyword parameter (default `True`) to return a Pandas `DataFrame` in which each property had its own column.

Starting with version 2.0, this behaviour is the default and the parameter has been removed.
====

=== Include node properties from Neo4j

Node properties such as names and descriptions are useful to understand the output of an algorithm, even if not needed to run the algorithm itself.
When a graph is projected from a Neo4j database, the `db_node_properties` client-only parameter for the `node_property.stream` method adds this information to the result.

In the following example, the `City` nodes have both a numeric and a `String` property.
The `stream` method retrieves the values of the database-only `name` property alongside the values of the projected `population` property.

[source,python,group=graph-project]
----
gds.run_cypher(
  """
  CREATE
    (m: City {name: "Malmö", population: 360000}),
    (l: City {name: "London", population: 8800000}),
    (s: City {name: "San Mateo", population: 105000}),

    (m)-[:FLY_TO]->(l),
    (l)-[:FLY_TO]->(m),
    (l)-[:FLY_TO]->(s),
    (s)-[:FLY_TO]->(l)
  """
)

G, result = gds.graph.project.native(
    "offices",
    {
        "City": {
            "properties": ["population"]
        }
    },
    "FLY_TO"
)

gds.graph.node_properties.stream(G, node_properties=["population"], db_node_properties=["name"])
----


== Read the graph topology

When reading the graph topology via the client equivalent to link:{gds-docs-base-uri}/management-ops/graph-reads/graph-stream-relationships/[`gds.graph.relationships.stream`], the return type is `RelationshipsDataFrame` (a subtype of `DataFrame`).

The result is a node-to-node table with a row for each connected pair of nodes.

[opts="header,autowidth",cols="1,1e,1e,1m"]
|===
| |sourceNodeId | targetNodeId | relationshipType

|0|node_id_1|node_id_2|REL_1
|1|node_id_2|node_id_3|REL_1
|2|node_id_2|node_id_4|REL_2
|=== 

This type includes the `by_rel_type` method to return a map between relationship types and lists of source node IDs and target node IDs respectively:

[subs="quotes"]
----
{
  "REL_1": [[_node_id_1_, _node_id_2_], [_node_id_2_, _node_id_3_]],
  "REL_2": [[_node_id_2_], [_node_id_4_]]
}
----

Example:

[source,python, group=graph-roundtrip, min-server-version=2.2.0]
----
gds.run_cypher(
  """
  CREATE
    (a:N)-[:REL]->(b:N),
    (b)-[:REL]->(c:N),
    (c)-[:REL]->(d:N),
    (d)-[:REL]->(a)
  """
)
G, _ = gds.graph.project.native("cycle", "N", "REL")

topology_by_rel_type = gds.graph.relationships.stream(G).by_rel_type()

assert list(topology_by_rel_type.keys()) == ["REL"]
sources, targets = topology_by_rel_type["REL"]
# In a cycle every node appears once as a source and once as a target
assert len(sources) == 4
assert set(sources) == set(targets)
----

== Apache Arrow speedup

All the streaming methods can run faster when the link:{gds-docs-base-uri}/installation/installation-apache-arrow/[Apache Arrow Flight Server] is enabled for GDS.

The server is available in GDS Enterprise and is *enabled by default on Aura Graph Analytics sessions and AuraDS*.